# Generated by Django 6.0 on 2026-01-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('cake', 'Cake'), ('brownie', 'Brownie')], max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
